#!/usr/bin/env python3
"""Static build audit for Sarothi.

No JDK or Android SDK is available where this runs, so nothing here compiles the
project. Instead it checks the classes of error that a compiler would catch and
that are cheap to find textually:

  1. `import com.ngi.sarothi.*` that resolves to no declared type.
  2. `R.<kind>.<name>` references with no matching resource in the *same* module
     (android.nonTransitiveRClass=true means a module only sees its own R).
  3. Manifest `android:name` entries pointing at classes that do not exist.
  4. `libs.<alias>` used in a build script but absent from the version catalog.
  5. Gradle `include(":x")` with no build script in that directory.

Deliberately conservative: anything ambiguous is reported as a warning, not an
error, so the output stays trustworthy rather than crying wolf.
"""

from __future__ import annotations

import os
import re
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ["core", "plugins", "app"]

errors: list[str] = []
warnings: list[str] = []

# ---------------------------------------------------------------- 1. imports

# Types Kotlin can import: class, interface, object, enum class, data class,
# sealed class/interface, annotation class, value class, typealias, and
# top-level functions/properties (file facades are harder, so functions are
# collected too).
DECL = re.compile(
    r"^\s*(?:public\s+|internal\s+|private\s+|abstract\s+|open\s+|sealed\s+|data\s+|"
    r"value\s+|annotation\s+|expect\s+|actual\s+|enum\s+|inline\s+|external\s+|suspend\s+|operator\s+|infix\s+|tailrec\s+)*"
    r"(class|interface|object|typealias|fun|val|var)\s+"
    # Extension declarations put a receiver before the name: `fun JsonObject.foo(...)`,
    # `val Foo.bar`. Capture the *last* identifier before `(` / `:` / `=` / `<` so the
    # member name is what gets indexed, not the receiver type.
    r"(?:[A-Za-z_][\w]*\s*\.\s*)?"
    r"(?:<[^>]*>\s*)?"
    r"([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)

# R is generated by AAPT at build time from this module's res/, and BuildConfig by
# AGP. Neither exists on disk, so neither can be resolved by a textual scan.
GENERATED_TYPES = {"R", "BuildConfig", "Manifest"}
PACKAGE = re.compile(r"^\s*package\s+([\w.]+)", re.MULTILINE)
IMPORT = re.compile(r"^\s*import\s+(com\.ngi\.sarothi\.[\w.]+)", re.MULTILINE)

# package -> set of declared names
declared: dict[str, set[str]] = defaultdict(set)
kt_files: list[Path] = []

for module in MODULES:
    for path in sorted((ROOT / module).rglob("*.kt")):
        kt_files.append(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        pkg_match = PACKAGE.search(text)
        if not pkg_match:
            errors.append(f"{rel(path)}: no package declaration")
            continue
        pkg = pkg_match.group(1)
        for _kind, name in DECL.findall(text):
            declared[pkg].add(name)
        # Nested types are reachable as Outer.Inner; record the outer name only.
        # Kotlin also lets you import a nested class directly, so collect those.
        for name in re.findall(r"\b(?:class|interface|object|enum class)\s+([A-Z]\w*)", text):
            declared[pkg].add(name)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


unresolved: dict[str, list[str]] = defaultdict(list)
for path in kt_files:
    text = path.read_text(encoding="utf-8", errors="replace")
    for imp in IMPORT.findall(text):
        pkg, _, symbol = imp.rpartition(".")
        if not pkg:
            continue
        if symbol in GENERATED_TYPES:
            continue
        if symbol in declared.get(pkg, set()):
            continue
        # Could be a nested type or a top-level member of a file whose package we
        # have not indexed under that name; check the symbol appears anywhere in
        # that package before calling it broken.
        if any(symbol in names for p, names in declared.items() if p == pkg):
            continue
        unresolved[imp].append(rel(path))

for imp, files in sorted(unresolved.items()):
    errors.append(
        f"unresolved import `{imp}` used by: {', '.join(sorted(set(files))[:4])}"
        + (f" (+{len(set(files)) - 4} more)" if len(set(files)) > 4 else "")
    )

# ------------------------------------------------------------- 2. resources

RES_KIND_DIR = {
    "drawable": ["drawable", "drawable-*"],
    "string": ["values"],
    "xml": ["xml"],
    "color": ["values"],
    "mipmap": ["mipmap", "mipmap-*"],
    "array": ["values"],
    "plurals": ["values"],
    "style": ["values"],
    "raw": ["raw"],
    "font": ["font"],
}
VALUE_NAME = re.compile(r'<(?:string|color|integer|bool|dimen|item|string-array|'
                        r'integer-array|array|plurals|style|declare-styleable)\s+name="([^"]+)"')

for module in MODULES:
    res_root = ROOT / module / "src" / "main" / "res"
    available: dict[str, set[str]] = defaultdict(set)
    if res_root.is_dir():
        for res_dir in sorted(res_root.iterdir()):
            if not res_dir.is_dir():
                continue
            kind = res_dir.name.split("-")[0]
            for f in res_dir.rglob("*"):
                if not f.is_file():
                    continue
                if kind in ("values",):
                    for name in VALUE_NAME.findall(f.read_text(encoding="utf-8", errors="replace")):
                        available["string"].add(name)
                        available["color"].add(name)
                        available["array"].add(name)
                        available["plurals"].add(name)
                        available["style"].add(name)
                elif f.suffix == ".xml" or kind in ("drawable", "mipmap", "raw", "font", "xml"):
                    available[kind].add(f.stem)
    # Framework resources are reached as android.R.* — excluded below.
    for path in sorted((ROOT / module).rglob("*.kt")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"(?<!android\.)\bR\.(\w+)\.(\w+)", text):
            kind, name = m.group(1), m.group(2)
            if kind not in RES_KIND_DIR:
                continue
            if name not in available.get(kind, set()):
                errors.append(
                    f"{rel(path)}: R.{kind}.{name} is referenced but :{module} declares no "
                    f"such resource (nonTransitiveRClass=true, so another module's copy "
                    f"is not visible here)"
                )

# ------------------------------------------------------------- 3. manifests

# :app is a declared-but-unwritten module (see README "What is missing"). Its
# absence is a known gap, not a regression, so it is reported as a warning --
# otherwise this audit could never go green and would train everyone to ignore
# it. Everything *inside* a module that does exist is still a hard error.
APP_ABSENT = not (ROOT / "app" / "build.gradle.kts").is_file()

for module in MODULES:
    manifest = ROOT / module / "src" / "main" / "AndroidManifest.xml"
    if not manifest.is_file():
        if module == "app" and APP_ABSENT:
            warnings.append("app/src/main/AndroidManifest.xml: missing (:app is not written yet)")
        elif module == "app":
            errors.append("app/src/main/AndroidManifest.xml: MISSING (:app has no manifest)")
        continue
    text = manifest.read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r'android:name="((?:com\.ngi\.sarothi|\.)[\w.]*)"', text):
        name = m.group(1)
        fqcn = name if name.startswith("com.") else f"com.ngi.sarothi.{name.lstrip('.')}"
        pkg, _, cls = fqcn.rpartition(".")
        if cls not in declared.get(pkg, set()):
            errors.append(f"{rel(manifest)}: android:name=\"{name}\" -> no class "
                          f"{cls} in package {pkg}")
    # Resource references from the manifest (@string/, @xml/, @drawable/).
    res_root = ROOT / module / "src" / "main" / "res"
    for m in re.finditer(r'@(string|xml|drawable|color|mipmap)/(\w+)', text):
        kind, name = m.group(1), m.group(2)
        found = False
        if res_root.is_dir():
            for res_dir in res_root.iterdir():
                if not res_dir.is_dir():
                    continue
                dkind = res_dir.name.split("-")[0]
                if dkind != kind and not (kind == "string" and dkind == "values"):
                    continue
                for f in res_dir.rglob("*"):
                    if f.is_file() and f.stem == name:
                        found = True
                    if found:
                        break
                if found:
                    break
            if not found and kind in ("string", "color"):
                for f in (res_root / "values").rglob("*.xml") if (res_root / "values").is_dir() else []:
                    if f'name="{name}"' in f.read_text(encoding="utf-8", errors="replace"):
                        found = True
                        break
        if not found:
            errors.append(f"{rel(manifest)}: @{kind}/{name} is referenced but :{module} "
                          f"does not define it")

# ---------------------------------------------------- 4. version catalog aliases

catalog_path = ROOT / "gradle" / "libs.versions.toml"
if catalog_path.is_file():
    catalog = tomllib.loads(catalog_path.read_text(encoding="utf-8"))
    valid: set[str] = set()
    for section in ("libraries", "plugins", "versions", "bundles"):
        for key in catalog.get(section, {}):
            valid.add(f"libs.{section[:-1] if section.endswith('s') else section}.{key.replace('-', '.')}")
    # Simpler: accept any libs.<a>.<b...> whose dotted tail matches a catalog key.
    lib_keys = {k for k in catalog.get("libraries", {})}
    plugin_keys = {k for k in catalog.get("plugins", {})}
    version_keys = {k for k in catalog.get("versions", {})}

    def norm(alias: str) -> str:
        return alias.replace(".", "-")

    for path in list(ROOT.glob("*.gradle.kts")) + list(ROOT.glob("*/build.gradle.kts")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"libs\.([\w.]+)", text):
            alias = m.group(1)
            parts = alias.split(".")
            if parts[0] in ("plugins", "libraries", "versions", "bundles"):
                tail = norm(".".join(parts[1:]))
                pool = {"plugins": plugin_keys, "libraries": lib_keys,
                        "versions": version_keys}.get(parts[0], set())
                if tail not in pool:
                    errors.append(f"{rel(path)}: libs.{alias} has no entry in "
                                  f"gradle/libs.versions.toml")
            else:
                # libs.foo.bar -> libraries "foo-bar", or libs.plugins.x
                if norm(alias) not in lib_keys and norm(alias) not in plugin_keys:
                    errors.append(f"{rel(path)}: libs.{alias} has no entry in "
                                  f"gradle/libs.versions.toml")

    # version.ref targets must exist
    for section in ("libraries", "plugins"):
        for key, value in catalog.get(section, {}).items():
            if isinstance(value, dict):
                ref = value.get("version", {}).get("ref") if isinstance(value.get("version"), dict) else None
                if ref and ref not in version_keys:
                    errors.append(f"libs.versions.toml: {section}.{key} references "
                                  f"version '{ref}' which is not defined")

# ------------------------------------------------------- 5. included projects

settings = ROOT / "settings.gradle.kts"
if settings.is_file():
    for m in re.finditer(r'include\(":(\w+)"\)', settings.read_text(encoding="utf-8")):
        module = m.group(1)
        build_file = ROOT / module / "build.gradle.kts"
        if not build_file.is_file():
            message = (f"settings.gradle.kts includes :{module} but "
                       f"{module}/build.gradle.kts does not exist")
            # Gradle tolerates an included project with no build script, so this
            # does not break `gradle :core:build`. It does mean no APK can be
            # produced until :app is written.
            (warnings if module == "app" else errors).append(message)

# ------------------------------------------- 6. scripts referenced but absent

# Build files, CMake and Kotlin error strings all tell the user to run a script.
# A message pointing at a file that does not exist is a broken promise in the UI,
# so treat it as an error rather than a style nit.
SCRIPT_REF = re.compile(r"scripts/([A-Za-z0-9_.\-]+\.(?:sh|py))")
referenced: dict[str, set[str]] = defaultdict(set)
scan_roots = [ROOT / "core", ROOT / "plugins", ROOT / "app", ROOT / ".github"]
scan_files = [ROOT / "build.gradle.kts", ROOT / "settings.gradle.kts", ROOT / "README.md"]
for root in scan_roots:
    if root.is_dir():
        scan_files.extend(p for p in root.rglob("*")
                          if p.is_file() and p.suffix in
                          {".kt", ".kts", ".xml", ".cpp", ".h", ".txt", ".yml", ".yaml", ".md"})
for path in scan_files:
    if not path.is_file() or ".git" in path.parts:
        continue
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        continue
    for name in SCRIPT_REF.findall(text):
        referenced[name].add(rel(path))

# Documented gaps. These are known-missing on purpose and recorded in the README;
# listing them here keeps the audit green today while still failing on any *new*
# dangling reference, which is the regression actually worth catching. Removing an
# entry once the file is written is the point of the list.
KNOWN_GAPS = {
    "build_espeak_ng.sh": (
        "cross-compiles espeak-ng for Piper TTS. Not written. TTS degrades to the "
        "Android system voice through a real code path -- EspeakPhonemizer."
        "availability() returns NO_NATIVE_LIBRARY -- so nothing fakes output."
    ),
}

for name, files in sorted(referenced.items()):
    script = ROOT / "scripts" / name
    if not script.is_file():
        message = (
            f"scripts/{name} is referenced by {len(files)} file(s) "
            f"({', '.join(sorted(files)[:3])}{' …' if len(files) > 3 else ''}) but does not exist"
        )
        if name in KNOWN_GAPS:
            warnings.append(f"{message} — known gap: {KNOWN_GAPS[name]}")
        else:
            errors.append(message)
    elif not os.access(script, os.X_OK):
        warnings.append(f"scripts/{name} exists but is not executable")

# ------------------------------------------------------------- report

print(f"scanned {len(kt_files)} Kotlin files across {MODULES}\n")

if errors:
    print(f"ERRORS ({len(errors)}) — these will fail the build:")
    for e in errors:
        print(f"  ✗ {e}")
else:
    print("ERRORS: none found")

if warnings:
    print(f"\nWARNINGS ({len(warnings)}):")
    for w in warnings:
        print(f"  ! {w}")

sys.exit(1 if errors else 0)
