#!/usr/bin/env python3
"""Static build audit for Sarothi.

No JDK or Android SDK is available where this runs, so nothing here compiles the
project. Instead it checks the classes of error that a compiler would catch and
that are cheap to find textually:

  1. `import com.ngi.sarothi.*` that resolves to no declared type.
  2. `R.<kind>.<name>` references with no matching resource in the *same* module
     (android.nonTransitiveRClass=true means a module only sees its own R).
  3. Manifest `android:name` entries pointing at classes that do not exist.
  4. `libs.<alias>` used in a build script but absent from the version catalog.
  5. Gradle `include(":x")` with no build script in that directory.

Deliberately conservative: anything ambiguous is reported as a warning, not an
error, so the output stays trustworthy rather than crying wolf.
"""

from __future__ import annotations

import bisect
import os
import re
import sys
import tomllib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MODULES = ["core", "plugins", "app"]

errors: list[str] = []
warnings: list[str] = []

# ---------------------------------------------------------------- 1. imports

# Types Kotlin can import: class, interface, object, enum class, data class,
# sealed class/interface, annotation class, value class, typealias, and
# top-level functions/properties (file facades are harder, so functions are
# collected too).
DECL = re.compile(
    r"^\s*(?:public\s+|internal\s+|private\s+|abstract\s+|open\s+|sealed\s+|data\s+|"
    r"value\s+|annotation\s+|expect\s+|actual\s+|enum\s+|inline\s+|external\s+|suspend\s+|operator\s+|infix\s+|tailrec\s+)*"
    r"(class|interface|object|typealias|fun|val|var)\s+"
    # Extension declarations put a receiver before the name: `fun JsonObject.foo(...)`,
    # `val Foo.bar`. Capture the *last* identifier before `(` / `:` / `=` / `<` so the
    # member name is what gets indexed, not the receiver type.
    r"(?:[A-Za-z_][\w]*\s*\.\s*)?"
    r"(?:<[^>]*>\s*)?"
    r"([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)

# R is generated by AAPT at build time from this module's res/, and BuildConfig by
# AGP. Neither exists on disk, so neither can be resolved by a textual scan.
GENERATED_TYPES = {"R", "BuildConfig", "Manifest"}
PACKAGE = re.compile(r"^\s*package\s+([\w.]+)", re.MULTILINE)
IMPORT = re.compile(r"^\s*import\s+(com\.ngi\.sarothi\.[\w.]+)", re.MULTILINE)

# package -> set of declared names
declared: dict[str, set[str]] = defaultdict(set)
kt_files: list[Path] = []

for module in MODULES:
    for path in sorted((ROOT / module).rglob("*.kt")):
        kt_files.append(path)
        text = path.read_text(encoding="utf-8", errors="replace")
        pkg_match = PACKAGE.search(text)
        if not pkg_match:
            errors.append(f"{rel(path)}: no package declaration")
            continue
        pkg = pkg_match.group(1)
        for _kind, name in DECL.findall(text):
            declared[pkg].add(name)
        # Nested types are reachable as Outer.Inner; record the outer name only.
        # Kotlin also lets you import a nested class directly, so collect those.
        for name in re.findall(r"\b(?:class|interface|object|enum class)\s+([A-Z]\w*)", text):
            declared[pkg].add(name)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


unresolved: dict[str, list[str]] = defaultdict(list)
for path in kt_files:
    text = path.read_text(encoding="utf-8", errors="replace")
    for imp in IMPORT.findall(text):
        pkg, _, symbol = imp.rpartition(".")
        if not pkg:
            continue
        if symbol in GENERATED_TYPES:
            continue
        if symbol in declared.get(pkg, set()):
            continue
        # Could be a nested type or a top-level member of a file whose package we
        # have not indexed under that name; check the symbol appears anywhere in
        # that package before calling it broken.
        if any(symbol in names for p, names in declared.items() if p == pkg):
            continue
        unresolved[imp].append(rel(path))

for imp, files in sorted(unresolved.items()):
    errors.append(
        f"unresolved import `{imp}` used by: {', '.join(sorted(set(files))[:4])}"
        + (f" (+{len(set(files)) - 4} more)" if len(set(files)) > 4 else "")
    )

# ------------------------------------------------------------- 2. resources

RES_KIND_DIR = {
    "drawable": ["drawable", "drawable-*"],
    "string": ["values"],
    "xml": ["xml"],
    "color": ["values"],
    "mipmap": ["mipmap", "mipmap-*"],
    "array": ["values"],
    "plurals": ["values"],
    "style": ["values"],
    "raw": ["raw"],
    "font": ["font"],
}
VALUE_NAME = re.compile(r'<(?:string|color|integer|bool|dimen|item|string-array|'
                        r'integer-array|array|plurals|style|declare-styleable)\s+name="([^"]+)"')

for module in MODULES:
    res_root = ROOT / module / "src" / "main" / "res"
    available: dict[str, set[str]] = defaultdict(set)
    if res_root.is_dir():
        for res_dir in sorted(res_root.iterdir()):
            if not res_dir.is_dir():
                continue
            kind = res_dir.name.split("-")[0]
            for f in res_dir.rglob("*"):
                if not f.is_file():
                    continue
                if kind in ("values",):
                    for name in VALUE_NAME.findall(f.read_text(encoding="utf-8", errors="replace")):
                        available["string"].add(name)
                        available["color"].add(name)
                        available["array"].add(name)
                        available["plurals"].add(name)
                        available["style"].add(name)
                elif f.suffix == ".xml" or kind in ("drawable", "mipmap", "raw", "font", "xml"):
                    available[kind].add(f.stem)
    # Framework resources are reached as android.R.* — excluded below.
    for path in sorted((ROOT / module).rglob("*.kt")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"(?<!android\.)\bR\.(\w+)\.(\w+)", text):
            kind, name = m.group(1), m.group(2)
            if kind not in RES_KIND_DIR:
                continue
            if name not in available.get(kind, set()):
                errors.append(
                    f"{rel(path)}: R.{kind}.{name} is referenced but :{module} declares no "
                    f"such resource (nonTransitiveRClass=true, so another module's copy "
                    f"is not visible here)"
                )

# ------------------------------------------------------------- 3. manifests

# :app is a declared-but-unwritten module (see README "What is missing"). Its
# absence is a known gap, not a regression, so it is reported as a warning --
# otherwise this audit could never go green and would train everyone to ignore
# it. Everything *inside* a module that does exist is still a hard error.
APP_ABSENT = not (ROOT / "app" / "build.gradle.kts").is_file()

for module in MODULES:
    manifest = ROOT / module / "src" / "main" / "AndroidManifest.xml"
    if not manifest.is_file():
        if module == "app" and APP_ABSENT:
            warnings.append("app/src/main/AndroidManifest.xml: missing (:app is not written yet)")
        elif module == "app":
            errors.append("app/src/main/AndroidManifest.xml: MISSING (:app has no manifest)")
        continue
    text = manifest.read_text(encoding="utf-8", errors="replace")
    for m in re.finditer(r'android:name="((?:com\.ngi\.sarothi|\.)[\w.]*)"', text):
        name = m.group(1)
        fqcn = name if name.startswith("com.") else f"com.ngi.sarothi.{name.lstrip('.')}"
        pkg, _, cls = fqcn.rpartition(".")
        if cls not in declared.get(pkg, set()):
            errors.append(f"{rel(manifest)}: android:name=\"{name}\" -> no class "
                          f"{cls} in package {pkg}")
    # Resource references from the manifest (@string/, @xml/, @drawable/).
    res_root = ROOT / module / "src" / "main" / "res"
    for m in re.finditer(r'@(string|xml|drawable|color|mipmap)/(\w+)', text):
        kind, name = m.group(1), m.group(2)
        found = False
        if res_root.is_dir():
            for res_dir in res_root.iterdir():
                if not res_dir.is_dir():
                    continue
                dkind = res_dir.name.split("-")[0]
                if dkind != kind and not (kind == "string" and dkind == "values"):
                    continue
                for f in res_dir.rglob("*"):
                    if f.is_file() and f.stem == name:
                        found = True
                    if found:
                        break
                if found:
                    break
            if not found and kind in ("string", "color"):
                for f in (res_root / "values").rglob("*.xml") if (res_root / "values").is_dir() else []:
                    if f'name="{name}"' in f.read_text(encoding="utf-8", errors="replace"):
                        found = True
                        break
        if not found:
            errors.append(f"{rel(manifest)}: @{kind}/{name} is referenced but :{module} "
                          f"does not define it")

# ---------------------------------------------------- 4. version catalog aliases

catalog_path = ROOT / "gradle" / "libs.versions.toml"
if catalog_path.is_file():
    catalog = tomllib.loads(catalog_path.read_text(encoding="utf-8"))
    valid: set[str] = set()
    for section in ("libraries", "plugins", "versions", "bundles"):
        for key in catalog.get(section, {}):
            valid.add(f"libs.{section[:-1] if section.endswith('s') else section}.{key.replace('-', '.')}")
    # Simpler: accept any libs.<a>.<b...> whose dotted tail matches a catalog key.
    lib_keys = {k for k in catalog.get("libraries", {})}
    plugin_keys = {k for k in catalog.get("plugins", {})}
    version_keys = {k for k in catalog.get("versions", {})}

    def norm(alias: str) -> str:
        return alias.replace(".", "-")

    for path in list(ROOT.glob("*.gradle.kts")) + list(ROOT.glob("*/build.gradle.kts")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for m in re.finditer(r"libs\.([\w.]+)", text):
            alias = m.group(1)
            parts = alias.split(".")
            if parts[0] in ("plugins", "libraries", "versions", "bundles"):
                tail = norm(".".join(parts[1:]))
                pool = {"plugins": plugin_keys, "libraries": lib_keys,
                        "versions": version_keys}.get(parts[0], set())
                if tail not in pool:
                    errors.append(f"{rel(path)}: libs.{alias} has no entry in "
                                  f"gradle/libs.versions.toml")
            else:
                # libs.foo.bar -> libraries "foo-bar", or libs.plugins.x
                if norm(alias) not in lib_keys and norm(alias) not in plugin_keys:
                    errors.append(f"{rel(path)}: libs.{alias} has no entry in "
                                  f"gradle/libs.versions.toml")

    # version.ref targets must exist
    for section in ("libraries", "plugins"):
        for key, value in catalog.get(section, {}).items():
            if isinstance(value, dict):
                ref = value.get("version", {}).get("ref") if isinstance(value.get("version"), dict) else None
                if ref and ref not in version_keys:
                    errors.append(f"libs.versions.toml: {section}.{key} references "
                                  f"version '{ref}' which is not defined")

# ------------------------------------------------------- 5. included projects

settings = ROOT / "settings.gradle.kts"
if settings.is_file():
    for m in re.finditer(r'include\(":(\w+)"\)', settings.read_text(encoding="utf-8")):
        module = m.group(1)
        build_file = ROOT / module / "build.gradle.kts"
        if not build_file.is_file():
            message = (f"settings.gradle.kts includes :{module} but "
                       f"{module}/build.gradle.kts does not exist")
            # Gradle tolerates an included project with no build script, so this
            # does not break `gradle :core:build`. It does mean no APK can be
            # produced until :app is written.
            (warnings if module == "app" else errors).append(message)

# ------------------------------------------- 6. scripts referenced but absent

# Build files, CMake and Kotlin error strings all tell the user to run a script.
# A message pointing at a file that does not exist is a broken promise in the UI,
# so treat it as an error rather than a style nit.
SCRIPT_REF = re.compile(r"scripts/([A-Za-z0-9_.\-]+\.(?:sh|py))")
referenced: dict[str, set[str]] = defaultdict(set)
scan_roots = [ROOT / "core", ROOT / "plugins", ROOT / "app", ROOT / ".github"]
scan_files = [ROOT / "build.gradle.kts", ROOT / "settings.gradle.kts", ROOT / "README.md"]
for root in scan_roots:
    if root.is_dir():
        scan_files.extend(p for p in root.rglob("*")
                          if p.is_file() and p.suffix in
                          {".kt", ".kts", ".xml", ".cpp", ".h", ".txt", ".yml", ".yaml", ".md"})
for path in scan_files:
    if not path.is_file() or ".git" in path.parts:
        continue
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        continue
    for name in SCRIPT_REF.findall(text):
        referenced[name].add(rel(path))

# Documented gaps. These are known-missing on purpose and recorded in the README;
# listing them here keeps the audit green today while still failing on any *new*
# dangling reference, which is the regression actually worth catching. Removing an
# entry once the file is written is the point of the list.
KNOWN_GAPS = {
    "build_espeak_ng.sh": (
        "cross-compiles espeak-ng for Piper TTS. Not written. TTS degrades to the "
        "Android system voice through a real code path -- EspeakPhonemizer."
        "availability() returns NO_NATIVE_LIBRARY -- so nothing fakes output."
    ),
}

for name, files in sorted(referenced.items()):
    script = ROOT / "scripts" / name
    if not script.is_file():
        message = (
            f"scripts/{name} is referenced by {len(files)} file(s) "
            f"({', '.join(sorted(files)[:3])}{' …' if len(files) > 3 else ''}) but does not exist"
        )
        if name in KNOWN_GAPS:
            warnings.append(f"{message} — known gap: {KNOWN_GAPS[name]}")
        else:
            errors.append(message)
    elif not os.access(script, os.X_OK):
        warnings.append(f"scripts/{name} exists but is not executable")

# ------------------------------------------- Kotlin traps CI already caught
#
# Every check below exists because the compiler hit it on a real build. They run on
# comment- and literal-stripped source (reusing check_kotlin_braces.strip_source, which
# blanks those regions to equal-length spaces so line numbers stay correct), so prose
# in a KDoc that mentions a forbidden API does not trip the gate.

sys.path.insert(0, str(Path(__file__).resolve().parent))
from check_kotlin_braces import strip_source  # noqa: E402

stripped: dict[Path, str] = {
    path: strip_source(path.read_text(encoding="utf-8", errors="replace"))
    for path in kt_files
}

# 1. Hex Long literals above Long.MAX_VALUE.
#    Java silently reinterprets 0xFF... as negative; Kotlin rejects it outright with
#    "Value out of range". This cost 3 errors in Blake2b.kt's IV table. Write such
#    constants as negative two's-complement literals instead.
HEX_LONG = re.compile(r"(?<![\w.])0[xX]([0-9a-fA-F]{16})(?![0-9a-fA-FuU])")
for path, text in stripped.items():
    for line_no, line in enumerate(text.split("\n"), 1):
        for m in HEX_LONG.finditer(line):
            if int(m.group(1), 16) > 0x7FFF_FFFF_FFFF_FFFF:
                errors.append(
                    f"{rel(path)}:{line_no}: hex literal 0x{m.group(1)} exceeds Long.MAX_VALUE; "
                    f"Kotlin will not reinterpret it as negative (use {int(m.group(1), 16) - (1 << 64)})"
                )

# 2. A trailing comma after the last entry of a `when`.
#    Kotlin allows trailing commas in declarations and argument lists but NOT here: the
#    parser then demands another condition and reports "'else' entry must be the last one"
#    plus a cascade of syntax errors. Hit in SarothiAgent.kt and PlanParser.kt.
WHEN_ELSE_COMMA = re.compile(r"^\s*else\s*->.*,\s*$")
for path, text in stripped.items():
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if WHEN_ELSE_COMMA.match(line):
            nxt = lines[i + 1].strip() if i + 1 < len(lines) else ""
            if nxt.startswith("}"):
                errors.append(
                    f"{rel(path)}:{i + 1}: trailing comma after a `when` else-branch "
                    f"(Kotlin expects another condition here)"
                )

# 3. `String.split { predicate }`.
#    String.split has overloads for Char, vararg String and Regex -- there is no
#    (Char) -> Boolean overload, so the trailing-lambda form cannot resolve. Hit in
#    VaultStores.tokenize(); use Regex("[^\\p{L}\\p{N}]+") to keep Bengali letters.
SPLIT_LAMBDA = re.compile(r"\.split\s*\{")
for path, text in stripped.items():
    for line_no, line in enumerate(text.split("\n"), 1):
        if SPLIT_LAMBDA.search(line):
            errors.append(
                f"{rel(path)}:{line_no}: `String.split {{ }}` has no predicate overload; "
                f"pass a Regex or a delimiter instead"
            )

# 4. An interface declared inside an `inner` class.
#    A nested interface is implicitly static and an inner class has no static members,
#    so Kotlin reports "'Interface' is prohibited here". Hit in SarothiAgent.TaskRun.
INNER_CLASS = re.compile(r"\binner\s+class\s+(\w+)")
for path, text in stripped.items():
    for m in INNER_CLASS.finditer(text):
        brace = text.find("{", m.end())
        if brace < 0:
            continue
        depth, end = 0, brace
        while end < len(text):
            if text[end] == "{":
                depth += 1
            elif text[end] == "}":
                depth -= 1
                if depth == 0:
                    break
            end += 1
        body = text[brace:end + 1]
        for nested in re.finditer(r"\b(?:sealed\s+|private\s+|internal\s+)*interface\s+(\w+)", body):
            line_no = text[:brace + nested.start()].count("\n") + 1
            errors.append(
                f"{rel(path)}:{line_no}: interface `{nested.group(1)}` is declared inside "
                f"inner class `{m.group(1)}`; move it to the enclosing class"
            )

# 5. Android / library members that are not in the public SDK at compileSdk 35.
#    Each entry was a real compile error, with the working replacement recorded so the
#    message tells the next person what to write instead.
NOT_IN_PUBLIC_SDK = {
    r"Settings\s*\.\s*ACTION_ACCESSIBILITY_DETAILS_SETTINGS":
        "@SystemApi/@hide; use the literal \"android.settings.ACCESSIBILITY_DETAILS_SETTINGS\"",
    r"Intent\s*\.\s*EXTRA_ACCESSIBILITY_COMPONENT_NAME":
        "does not exist; AOSP Settings reads Intent.EXTRA_COMPONENT_NAME",
    r"\.roleDescription\b":
        "AccessibilityNodeInfo has no getRoleDescription() in the framework SDK; read "
        "extras.getCharSequence(\"AccessibilityNodeInfo.roleDescription\") or use "
        "AccessibilityNodeInfoCompat",
    r"OrtEnvironment[\s\S]{0,80}?\.createSessionOptions\s*\(|\benvironment\.createSessionOptions\s*\(":
        "OrtEnvironment has no such factory; construct ai.onnxruntime.OrtSession.SessionOptions()",
}
for path, text in stripped.items():
    for pattern, why in NOT_IN_PUBLIC_SDK.items():
        for m in re.finditer(pattern, text):
            line_no = text[:m.start()].count("\n") + 1
            errors.append(f"{rel(path)}:{line_no}: {m.group(0).strip()} is not public API -- {why}")

# 6. Named arguments that do not match the declared parameter.
#    Only checks functions declared exactly once in this repo and only reports a name
#    that appears in no declaration of it, so stdlib calls and genuine overloads are
#    never flagged. Hit twice: PluginAvailability.unavailable takes `fixAction`, but
#    PluginManager.kt and MetaPlugins.kt passed `fix =`.
# Balanced-paren scan, not `\(([^)]*)\)`: a parameter typed as a function --
# `onProgress: (DownloadProgress) -> Unit = {}` -- closes the naive pattern early and
# silently drops every parameter after it, which produced 13 phantom mismatches.
FUN_HEAD = re.compile(r"\bfun\s+(?:[\w.<>]+\s*\.\s*)?([A-Za-z_]\w*)\s*\(")
TYPE_DECL = re.compile(
    r"^\s*(?:(?:public|private|internal|protected|abstract|open|sealed|data|value|"
    r"annotation|enum|inner|expect|actual)\s+)*(?:class|interface|object)\s+([A-Za-z_]\w*)"
)

# Declarations are indexed both bare and qualified by their enclosing type. The
# qualified index is what makes the check usable at all: `unavailable` is declared three
# times (PluginAvailability, VoiceAvailability, VisionGrounding) with different parameter
# names, so an unqualified lookup is ambiguous and would have to be skipped.
# A `companion object` header captures no name, so it is skipped and the surrounding
# class becomes the owner -- which is exactly how these factories are called.
def _matching_paren(text: str, open_index: int) -> int:
    """Index of the `)` closing the `(` at open_index, or -1 if unbalanced."""
    depth = 0
    for i in range(open_index, len(text)):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


bare_params: dict[str, set] = defaultdict(set)
bare_count: dict[str, int] = defaultdict(int)
owned_params: dict[tuple, set] = defaultdict(set)
owned_count: dict[tuple, int] = defaultdict(int)

for path, text in stripped.items():
    lines = text.split("\n")
    indents = [len(ln) - len(ln.lstrip()) for ln in lines]
    newlines = [i for i, ch in enumerate(text) if ch == "\n"]
    owners = []  # (line index, indent, type name)
    for idx, ln in enumerate(lines):
        tm = TYPE_DECL.match(ln)
        if tm:
            owners.append((idx, indents[idx], tm.group(1)))

    for m in FUN_HEAD.finditer(text):
        close = _matching_paren(text, m.end() - 1)
        if close < 0:
            continue
        name = m.group(1)
        # The identifier before each `:` is the parameter name. String literals are
        # already blanked, so a default like `label: String = "a:b"` adds no noise, and
        # a generic bound `<T : Any>` only ever widens the allowed set.
        pnames = set(re.findall(r"\b([A-Za-z_]\w*)\s*:", text[m.end():close]))
        line_idx = bisect.bisect_right(newlines, m.start())
        indent = indents[line_idx]
        owner = next(
            (tname for tidx, tindent, tname in reversed(owners) if tidx < line_idx and tindent < indent),
            None,
        )
        bare_count[name] += 1
        bare_params[name] |= pnames
        if owner:
            owned_count[(owner, name)] += 1
            owned_params[(owner, name)] |= pnames

# A named argument must sit right after `(` or `,`, and its `=` must not be the first
# half of `==`. Without those guards the pattern also matches parameter defaults in
# declarations and comparisons passed positionally (`indexAlpha(p, s, i, j1, refLane == lane)`).
NAMED_ARG = re.compile(r"(?<=[(,])\s*([A-Za-z_]\w*)\s*=(?!=)")
# Bounded window: slicing the whole prefix per match was O(n^2) and made the audit take
# 44 s. No argument list in this repo comes close to this many characters.
LOOKBACK = 4000
CALLEE = re.compile(r"(?:(?P<qual>[A-Za-z_]\w*)\s*\.\s*)?(?P<fn>[A-Za-z_]\w*)\s*$")

# Repo-declared functions sharing a name with a stdlib member that takes named arguments
# of its own: `String.contains(other, ignoreCase = true)` is correct stdlib, and without
# types it cannot be told apart from this repo's own `contains(key)`.
STDLIB_NAME_COLLISIONS = {
    "contains", "copy", "equals", "hashCode", "toString", "format", "split", "replace",
    "substring", "compareTo", "matches", "get", "set", "add", "remove", "put", "of",
    "from", "parse", "run", "let", "apply", "also", "filter", "map", "forEach", "with",
    "require", "check", "invoke", "close", "open", "read", "write", "joinToString",
}

for path, text in stripped.items():
    newlines = [i for i, ch in enumerate(text) if ch == "\n"]
    for m in NAMED_ARG.finditer(text):
        arg = m.group(1)
        window = text[max(0, m.start() - LOOKBACK):m.start()].rstrip()
        # Walk back to the unmatched `(` that opens this argument list.
        depth, i = 0, len(window) - 1
        while i >= 0:
            ch = window[i]
            if ch == ")":
                depth += 1
            elif ch == "(":
                if depth == 0:
                    break
                depth -= 1
            i -= 1
        if i < 0:
            continue
        cm = CALLEE.search(window[:i])
        if not cm:
            continue
        fn, qual = cm.group("fn"), cm.group("qual")
        if fn in STDLIB_NAME_COLLISIONS:
            continue
        # Only judge a call whose target is unambiguous: qualified when the receiver is
        # a type this repo declares, otherwise a name declared exactly once.
        if qual and owned_count.get((qual, fn), 0) == 1:
            allowed = owned_params[(qual, fn)]
        elif not qual and bare_count.get(fn, 0) == 1:
            allowed = bare_params[fn]
        else:
            continue
        if arg in allowed:
            continue
        line_no = bisect.bisect_right(newlines, m.start()) + 1
        target = f"{qual}.{fn}" if qual else fn
        errors.append(
            f"{rel(path)}:{line_no}: `{target}(... {arg} = ...)` -- no parameter `{arg}`; "
            f"declared parameters are {sorted(allowed)}"
        )

# 7. An `if` expression used as a `+` operand without parentheses.
#    `a + if (c) b else "" + d` parses as `a + if (c) b else ("" + d)`, because the
#    else-branch extends as far as it can. The result compiles cleanly and reads
#    correctly, but when the condition is true the trailing text silently vanishes.
#    Found three times in plugin summaries: an alarm set for particular weekdays lost
#    its label and its "the Clock app is open" sentence, a weather lookup lost "Sarothi
#    will not guess coordinates", and a Home Assistant listing lost its entity list.
IF_PLUS_OPERAND = re.compile(
    r"^\s*(?:.*\+\s*)?if\s*\(.*\)\s*.+?\belse\b\s*(?:\"[^\"]*\"|\w[\w.]*)\s*\+\s*$"
)
COMMENT_LINE = re.compile(r"^\s*(?://|/\*|\*)")
# This one runs on the raw source, not on `stripped`: the pattern is defined by its
# string literals, and blanking them (which is what makes every other check immune to
# prose) removes exactly what it has to match. Comment lines are skipped instead, which
# is the narrower exemption and cannot hide a real expression.
for path in kt_files:
    for line_no, line in enumerate(
        path.read_text(encoding="utf-8", errors="replace").split("\n"), 1
    ):
        if COMMENT_LINE.match(line):
            continue
        if IF_PLUS_OPERAND.match(line):
            errors.append(
                f"{rel(path)}:{line_no}: an `if` expression is a `+` operand without "
                f"parentheses, so the `else` branch swallows everything after it -- "
                f"wrap the whole `if` in parens"
            )

# ------------------------------------------------------------- report

print(f"scanned {len(kt_files)} Kotlin files across {MODULES}\n")

if errors:
    print(f"ERRORS ({len(errors)}) — these will fail the build:")
    for e in errors:
        print(f"  ✗ {e}")
else:
    print("ERRORS: none found")

if warnings:
    print(f"\nWARNINGS ({len(warnings)}):")
    for w in warnings:
        print(f"  ! {w}")

sys.exit(1 if errors else 0)
